<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */

$_product = $block->getProduct();
$_wishlistHelper = $this->helper('MageKey\AddToLinks\Helper\Wishlist');

?>
<?php if ($_wishlistHelper->isAllow()): ?>
    <a href="#"
       class="action towishlist"
       data-mage-init='{
           "MageKey_AddToLinks/js/add-to-wishlist": {
               "productId": <?php /* @escapeNotVerified */ echo $_product->getId(); ?>,
               "addParams": <?php /* @escapeNotVerified */ echo $_wishlistHelper->getAddParams($_product); ?>,
               "removeParams": <?php /* @escapeNotVerified */ echo $_wishlistHelper->getRemoveParams(); ?>,
               "loginUrl": "<?php /* @escapeNotVerified */ echo $_wishlistHelper->getLoginUrl(); ?>"
           }
       }'
       data-action="add-to-wishlist">
        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
    </a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $block->getWishlistOptionsJson() ?>
        }
    }
</script>
