<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var $block \Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist */

$_product = $block->getProduct();
$_wishlistHelper = $this->helper('MageKey\AddToLinks\Helper\Wishlist');

?>
<?php if ($_wishlistHelper->isAllow()): ?>
    <a class="action towishlist"
       title="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
       aria-label="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
       data-mage-init='{
           "MageKey_AddToLinks/js/add-to-wishlist": {
               "productId": <?= /* @escapeNotVerified */ $_product->getId(); ?>,
               "addParams": <?= /* @escapeNotVerified */ $_wishlistHelper->getAddParams($_product); ?>,
               "removeParams": <?= /* @escapeNotVerified */ $_wishlistHelper->getRemoveParams(); ?>,
               "loginUrl": "<?= /* @escapeNotVerified */ $_wishlistHelper->getLoginUrl(); ?>"
           }
       }'
       data-action="add-to-wishlist"
       role="button">
        <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
    </a>
<?php endif; ?>
