<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */

$_product = $block->getProduct();
$_compareHelper = $this->helper('MageKey\AddToLinks\Helper\Compare');

?>
<a href="#"
   class="action tocompare"
   title="<?= $block->escapeHtml(__('Add to Compare')); ?>"
   aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>"
   data-mage-init='{
       "MageKey_AddToLinks/js/add-to-compare": {
           "productId": <?= /* @escapeNotVerified */ $_product->getId(); ?>,
           "addParams": <?= /* @escapeNotVerified */ $_compareHelper->getAddParams($_product); ?>,
           "removeParams": <?= /* @escapeNotVerified */ $_compareHelper->getRemoveParams($_product); ?>
       }
   }'
   role="button">
    <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
</a>
