<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

use MageKey\AddToLinks\Model\Config\Source\Templates as SourceTemplates;

/** @var $block \Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare */

$_product = $block->getProduct();
$_dataHelper = $this->helper(\MageKey\AddToLinks\Helper\Data::class);
$_compareHelper = $this->helper(\MageKey\AddToLinks\Helper\Compare::class);

?>
<?php if ($_dataHelper->getTemplate() == SourceTemplates::TEMPLATE_CHECKBOX) : ?>
    <div class="mgk-addtolink action tocompare template-checkbox" 
         aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>">
        <input type="checkbox"
               id="mgk-addtolink-compare-list-<?= /* @escapeNotVerified */ $_product->getId(); ?>"
               data-mage-init='{
                   "MageKey_AddToLinks/js/add-to-compare": {
                       "productId": <?= /* @escapeNotVerified */ $_product->getId(); ?>,
                       "addParams": <?= /* @escapeNotVerified */ $_compareHelper->getAddParams($_product); ?>,
                       "removeParams": <?= /* @escapeNotVerified */ $_compareHelper->getRemoveParams($_product); ?>
                   }
               }'/><label for="mgk-addtolink-compare-list-<?= /* @escapeNotVerified */ $_product->getId(); ?>"><?= /* @escapeNotVerified */ __('Add to Compare') ?></label>
    </div>
<?php else : ?>
    <a href="#"
       class="mgk-addtolink action tocompare"
       title="<?= $block->escapeHtml(__('Add to Compare')); ?>"
       aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>"
       data-mage-init='{
           "MageKey_AddToLinks/js/add-to-compare": {
               "productId": <?= /* @escapeNotVerified */ $_product->getId(); ?>,
               "addParams": <?= /* @escapeNotVerified */ $_compareHelper->getAddParams($_product); ?>,
               "removeParams": <?= /* @escapeNotVerified */ $_compareHelper->getRemoveParams($_product); ?>
           }
       }'
       role="button">
        <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
    </a>
<?php endif; ?>